spring:
  application:
    name: dpp-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost
        port: ${server.port}
  datasource:
    url: jdbc:mysql://101.42.54.40:3306/dpp?useLocalSessionState=true
    username: rj14
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 101.42.54.40
      password: ${REDIS_PASSWORD}

server:
  address: localhost
  port: 9008

