spring:
  cloud:
    gateway:
      routes:
        - id: dpp-auth
          uri: lb://dpp-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: dpp-system
          uri: lb://dpp-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1