server:
  port: 11887q

spring:
  application:
    # 应用名称
    name: dpp-auth

  cloud:
    nacos:
      # 服务注册与发现
      discovery:
        server-addr: 101.42.54.40
        port: 8848
        username: nacos
        password: ${n.d.password}
        weight: 1