name: Build and Publish JARs

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Java 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21' # 根据项目需要调整 Java 版本

      # 构建项目并打包 JAR 文件
      - name: Build and package
        run: |
          ./mvnw clean package -DskipTests

      # 发布 JAR 文件到 GitHub Packages
      - name: Publish JARs to GitHub Packages
        run: |
          ./mvnw deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
